### ISSUE TITLE
Rel coin amount precision losing on maker order creation

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#177]
1) Try to sell 100 KMD for 15 DEX: will be created 100 KMD for 15 DEX order as expected
![image](https://user-images.githubusercontent.com/24797699/82572672-e6fa4e80-9bae-11ea-8f11-9f1e537e8a4c.png)
![image](https://user-images.githubusercontent.com/24797699/82572686-eb266c00-9bae-11ea-8599-fa1776d4cbf0.png)

2) Try to sell 100.5 KMD for 15 DEX: will be created different rel amount order when 15 DEX is expected
![image](https://user-images.githubusercontent.com/24797699/82572699-efeb2000-9bae-11ea-863e-2262a44f42fa.png)
![image](https://user-images.githubusercontent.com/24797699/82572709-f37ea700-9bae-11ea-9feb-6e5603b4e280.png)

Please note that mm2 supports rational numbers orderbook format to keep precision

**Comment by Milerius** [comment]
solved #180

**Comment by tonymorony** [comment]
![image](https://user-images.githubusercontent.com/24797699/84493896-c2d3ee00-acd2-11ea-9529-2a9e88f377f9.png)

![image](https://user-images.githubusercontent.com/24797699/84493956-dda66280-acd2-11ea-8b9d-bedfcf42af12.png)

**Comment by tonymorony** [comment]
@Milerius  We should solve this problem globally by rational numbers usage everywhere instead of decimals and decimals division

@artemii235 kindly agreed to make a little session next week to help with these numbers usage explanation

**Comment by Milerius** [comment]
As I said during the meeting, this problem is more of a visual problem than a backend problem, currently the matching system has been changed and we are achieving 100% matching on the initial order, but we actually have to display use a specific display to limit the infinite number after the decimal point of certain calculations.

I am open to the use of rational numbers, but I don't think that will correct this display problem, moreover I find it hard to see how we can correctly convert an order which has a floating number into a rational number , example:

If i want `7.77` Komodo for `3.33` DEX, the rational representation of this operation will not be precise

Interesting topic on the subject: 
https://stackoverflow.com/questions/51142275/exact-value-of-a-floating-point-number-as-a-rational

**Comment by artemii235** [comment]
> If i want 7.77 Komodo for 3.33 DEX, the rational representation of this operation will not be precise

The rational representation *will* be precise because you can simply submit the following call to MM2 (I replaced the pair to RICK/MORTY):
```
{
"method":"sell",
"base":"RICK",
"rel":"MORTY",
"volume":"7.77",
"price":{
  "numer":"333",
  "denom":"777",
}
}
```
Which will result to following order being created:
```
{
  "result":{
    "action":"Sell",
    "base":"RICK",
    "base_amount":"7.77",
    "base_amount_rat":[
      [
        1,
        [
          777
        ]
      ],
      [
        1,
        [
          100
        ]
      ]
    ],
    "dest_pub_key":"0000000000000000000000000000000000000000000000000000000000000000",
    "match_by":{
      "type":"Any"
    },
    "method":"request",
    "rel":"MORTY",
    "rel_amount":"3.33",
    "rel_amount_rat":[
      [
        1,
        [
          333
        ]
      ],
      [
        1,
        [
          100
        ]
      ]
    ],
    "sender_pubkey":"564fdca883e9cdf4501b5b983a2d27f9999301933da598b97455600eea4e6f62",
    "uuid":"b8ddb66b-8f45-4855-b21c-5615a4d901e3"
  }
}
```
Of course, you might have issues with such `333/777` price displaying in GUI, but you can consider some parts of such number as not significant for display and simply show `0,42857142` or let user know that it is *approximate*: `˜0,428571428571429` or even display this as `333/777` fraction right away 🙂 

The main point is that GUI backend simply should *not* use floating point or even decimal types for *any* financial calculation because it will always lose precision at some point and lead to such "my order is not matching" or " volume is slightly different" bugs.

Using rational will allow to avoid it because you can simply create e.g. `1/3` volume order and it will then cut to required number of coin decimals upon swap transaction creation. E.g. for BTC and KMD it will be `0.33333333`, but for ETH it will be `0.333333333333333333` because ETH has 18 decimals.
