### ISSUE TITLE
Display of Transaction Fee at ETH -> TUSD

### ISSUE THREAD

**Issue by naezith** [KomodoPlatform/atomicDEX-Pro#21]
![image](https://user-images.githubusercontent.com/6732486/77257751-4f987e00-6c87-11ea-8f91-e296a02f825c.png)

`tx_fee + erc_fees`

Please confirm that this is correct.

**Comment by cipig** [comment]
i have a strange txfee problem when only one of the coins is erc20, DOGE-USDC
![image](https://user-images.githubusercontent.com/32116761/84391843-0a7e4b00-abe9-11ea-88b6-50042d9163b0.png)

```
QMap(("erc_fees", QVariant(QString, "4.36145718"))("input_final_value", QVariant(QString, "263.74066329"))("is_ticker_of_fees_eth", QVariant(bool, false))("trade_fee", QVariant(QString, "0.35111286"))("tx_fee", QVariant(QString, "8.72291436")))
qml: Getting Trade info with parameters:  DOGE USDC 272.81469051  -  Result:  {"erc_fees":"4.36145718","input_final_value":"263.74066329","is_ticker_of_fees_eth":false,"trade_fee":"0.35111286","tx_fee":"8.72291436"}
QMap(("erc_fees", QVariant(QString, "4.36145718"))("input_final_value", QVariant(QString, "272.82107063"))("is_ticker_of_fees_eth", QVariant(bool, false))("trade_fee", QVariant(QString, "0.36281441"))("tx_fee", QVariant(QString, "8.72291436")))
qml: Getting Trade info with parameters:  DOGE USDC 281.9067994  -  Result:  {"erc_fees":"4.36145718","input_final_value":"272.82107063","is_ticker_of_fees_eth":false,"trade_fee":"0.36281441","tx_fee":"8.72291436"}
```

but does not happen the same way with KMD-USDC
![image](https://user-images.githubusercontent.com/32116761/84392011-49ac9c00-abe9-11ea-9d84-d77af0df9942.png)

it looks like the fee shown (after the +) is calculated based on taker coin (DOGE/KMD) instead of maker coin

**Comment by naezith** [comment]
Is it about backend? @Milerius

**Comment by cipig** [comment]
fixed

trade tab now shows this
![image](https://user-images.githubusercontent.com/32116761/84510438-a3c66380-acb4-11ea-8e18-ddf999856de8.png)

and the erc20 tx used this
![image](https://user-images.githubusercontent.com/32116761/84510534-c9536d00-acb4-11ea-8da9-54565b9e2ec7.png)

diff is because `get_trade_fee` use 150000 gas limit, but only 47% of the gas was actually used later

**Comment by tonymorony** [comment]
great catch and thanks for fix :)
