### ISSUE TITLE
Custom fee calculation for ERC-20

### ISSUE THREAD

**Issue by naezith** [KomodoPlatform/atomicDEX-Pro#27]
![image](https://user-images.githubusercontent.com/6732486/77443246-00278e80-6dfc-11ea-9452-b4c262a1cb7b.png)

At this view, I need to check if user has enough balance for this withdraw call.

I do the check `balance >= amount` at the moment. But it's more complex than that of course.

User enters `amount`, `gas` (Gwei), `gas_price` (Gwei).  And I have the info for `ETH balance`.

What the correct statement should be?

Is it `erc20_coin_balance >= amount && eth_balance >= (gas * gas_price)/1,000,000,000`?

But then if `erc20_coin` is ETH, is it being `eth_balance >= amount + (gas * gas_price)/1,000,000,000`?

So there are two cases.

**Comment by artemii235** [comment]
Hi @naezith 

Yes, statements above are correct:
`erc20_coin_balance >= amount && eth_balance >= (gas * gas_price)/1,000,000,000` for ERC20 and `eth_balance >= amount + (gas * gas_price)/1,000,000,000` for ETH.

Please also note that `gas limit` is special unit measuring how much computational work transaction will take [cf](https://ethereum.stackexchange.com/a/62). It is not measured in Gwei so you should use `Gas limit` title instead of `Gas [Gwei]`.
